// <auto-generated />
using System;
using Auth.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auth.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDb))]
    [Migration("20260929190000_RevenueCapture")]
    partial class RevenueCapture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("After")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Before")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("OccuredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "ActorId");

                    b.HasIndex("OrganizationId", "OccuredAt");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("Auth.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("SettingsVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Auth.Domain.OrganizationBranding", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Favicon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoAlt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoDark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoLight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrivacyUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secondary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationId");

                    b.ToTable("Brandings");
                });

            modelBuilder.Entity("Auth.Domain.OrganizationLocalization", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowHour12Override")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowLocaleOverride")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowThemeOverride")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTimeZoneOverride")
                        .HasColumnType("bit");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatePattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstDayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("Hour12")
                        .HasColumnType("bit");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberDecimals")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseGroupping")
                        .HasColumnType("bit");

                    b.Property<string>("WeekNumbering")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationId");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("Auth.Domain.OrganizationLogo", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OrganizationId");

                    b.ToTable("Logos");
                });

            modelBuilder.Entity("Auth.Domain.OrganizationMembership", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ApprovalLimit")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Auth.Domain.OrganizationSecurityPolicy", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessTokenMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("AllowPinSignIn")
                        .HasColumnType("bit");

                    b.Property<int>("IdleUnlockSeconds")
                        .HasColumnType("int");

                    b.Property<int>("LockoutMinutes")
                        .HasColumnType("int");

                    b.Property<int>("LockoutThreshold")
                        .HasColumnType("int");

                    b.Property<bool>("PasswordComplexity")
                        .HasColumnType("bit");

                    b.Property<int>("PasswordHistory")
                        .HasColumnType("int");

                    b.Property<int>("PasswordMinLength")
                        .HasColumnType("int");

                    b.Property<int>("PinLength")
                        .HasColumnType("int");

                    b.Property<int>("RefreshTokenDays")
                        .HasColumnType("int");

                    b.HasKey("OrganizationId");

                    b.ToTable("SecurityPolicies");
                });

            modelBuilder.Entity("Auth.Domain.PersonPermissionOverride", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Granted")
                        .HasColumnType("bit");

                    b.HasKey("OrganizationId", "UserId", "Permission");

                    b.ToTable("PermissionOverrides");
                });

            modelBuilder.Entity("Auth.Domain.PersonRole", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrganizationId", "UserId", "RoleId");

                    b.HasIndex("OrganizationId", "RoleId");

                    b.ToTable("PersonRoles");
                });

            modelBuilder.Entity("Auth.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Auth.Domain.Role", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Auth.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrganizationId", "RoleId", "Permission");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Auth.Domain.Setup.CostCategoryLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CostCategoryLookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RunningCosts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RepairsAndUpkeep"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CrewCosts"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FixedCommitments"
                        });
                });

            modelBuilder.Entity("Auth.Domain.RevenueRecord", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<Guid>("CapturedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<bool>("CorrectedAfterDate")
                        .HasColumnType("bit");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("Reason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "BusinessDate");

                    b.HasIndex("OrganizationId", "VehicleId", "BusinessDate")
                        .IsUnique();

                    b.ToTable("RevenueRecords");
                });

            modelBuilder.Entity("Auth.Domain.Setup.FleetVehicle", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("LeftOn")
                        .HasColumnType("date");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "CompanyId");

                    b.HasIndex("OrganizationId", "Registration")
                        .IsUnique();

                    b.ToTable("FleetVehicle");
                });

            modelBuilder.Entity("Auth.Domain.Setup.OrganizationSettingsVersion", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("After")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Before")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "ActorId");

                    b.HasIndex("OrganizationId", "Version")
                        .IsUnique();

                    b.ToTable("OrganizationSettingsVersion");
                });

            modelBuilder.Entity("Auth.Domain.Setup.PsvCompany", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ArchivedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("PsvCompany");
                });

            modelBuilder.Entity("Auth.Domain.Setup.RecurrenceFrequencyLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceFrequencyLookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Daily"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weekly"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monthly"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Setup.RecurringAllocation", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "VehicleId");

                    b.HasIndex("OrganizationId", "VersionId", "VehicleId")
                        .IsUnique();

                    b.ToTable("RecurringAllocation");
                });

            modelBuilder.Entity("Auth.Domain.Setup.RecurringItem", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("StoppedFrom")
                        .HasColumnType("date");

                    b.HasKey("OrganizationId", "Id");

                    b.ToTable("RecurringItem");
                });

            modelBuilder.Entity("Auth.Domain.Setup.RecurringKindLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecurringKindLookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cost"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Savings"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Setup.RecurringVersion", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("End")
                        .HasColumnType("date");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<bool>("LastDay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("Category");

                    b.HasIndex("Frequency");

                    b.HasIndex("Kind");

                    b.HasIndex("OrganizationId", "ItemId", "Revision")
                        .IsUnique();

                    b.ToTable("RecurringVersion");
                });

            modelBuilder.Entity("Auth.Domain.Setup.SetupCompanyScope", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrganizationId", "UserId", "CompanyId");

                    b.HasIndex("OrganizationId", "CompanyId");

                    b.ToTable("SetupCompanyScopes");
                });

            modelBuilder.Entity("Auth.Domain.Setup.SetupDataScope", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllCompanies")
                        .HasColumnType("bit");

                    b.HasKey("OrganizationId", "UserId");

                    b.ToTable("SetupDataScopes");
                });

            modelBuilder.Entity("Auth.Domain.Setup.SetupVehicleScope", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrganizationId", "UserId", "VehicleId");

                    b.HasIndex("OrganizationId", "VehicleId");

                    b.ToTable("SetupVehicleScopes");
                });

            modelBuilder.Entity("Auth.Domain.Setup.VehicleTarget", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WeeklyAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "VehicleId", "Revision")
                        .IsUnique();

                    b.ToTable("VehicleTarget");
                });

            modelBuilder.Entity("Auth.Domain.TrustedDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("TrustExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.ToTable("TrustedDevices");
                });

            modelBuilder.Entity("Auth.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PausedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("PinHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SecurityVersion")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] <> ''");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Auth.Domain.UserPreference", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("FontScale")
                        .HasColumnType("float");

                    b.Property<bool?>("Hour12")
                        .HasColumnType("bit");

                    b.Property<string>("Locale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReducedMotion")
                        .HasColumnType("bit");

                    b.Property<string>("ThemeMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationId", "UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Auth.Domain.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Consumed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Purpose");

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("Auth.Domain.AuditEvent", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.OrganizationBranding", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.OrganizationLocalization", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.OrganizationLogo", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.OrganizationMembership", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.OrganizationSecurityPolicy", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.PersonPermissionOverride", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.PersonRole", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.RefreshToken", b =>
                {
                    b.HasOne("Auth.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Role", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.RolePermission", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Setup.FleetVehicle", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Setup.PsvCompany", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Setup.OrganizationSettingsVersion", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Setup.PsvCompany", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.RevenueRecord", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Setup.FleetVehicle", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Setup.RecurringAllocation", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Setup.FleetVehicle", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Setup.RecurringVersion", null)
                        .WithMany("Allocations")
                        .HasForeignKey("OrganizationId", "VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Setup.RecurringItem", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Setup.RecurringVersion", b =>
                {
                    b.HasOne("Auth.Domain.Setup.CostCategoryLookup", null)
                        .WithMany()
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Auth.Domain.Setup.RecurrenceFrequencyLookup", null)
                        .WithMany()
                        .HasForeignKey("Frequency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Setup.RecurringKindLookup", null)
                        .WithMany()
                        .HasForeignKey("Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Setup.RecurringItem", null)
                        .WithMany("Versions")
                        .HasForeignKey("OrganizationId", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Setup.SetupCompanyScope", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Setup.PsvCompany", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Setup.SetupDataScope", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Setup.SetupVehicleScope", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Setup.FleetVehicle", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Setup.VehicleTarget", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Setup.FleetVehicle", null)
                        .WithMany("Targets")
                        .HasForeignKey("OrganizationId", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.TrustedDevice", b =>
                {
                    b.HasOne("Auth.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.UserPreference", b =>
                {
                    b.HasOne("Auth.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auth.Domain.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.VerificationCode", b =>
                {
                    b.HasOne("Auth.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Setup.FleetVehicle", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Auth.Domain.Setup.RecurringItem", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Auth.Domain.Setup.RecurringVersion", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
