"use client";

import { useEffect, useState } from "react";
import { requestSetup } from "./requestSetup";
import type { Page, Person, Permission, PermissionGroup, Role } from "./setupTypes";

const roleDefaults: Record<string, string[]> = {
  "Office admin": ["dash.revenue", "dash.costs", "dash.gaps", "dash.commitments", "dash.edits", "revenue.view", "revenue.correct", "bills.view", "bills.capture", "commitments.view", "commitments.manage", "reports.view", "reports.export", "companies.manage", "vehicles.manage", "people.view", "people.manage", "audit.view"],
  "Fleet manager": ["dash.float", "dash.revenue", "dash.costs", "dash.gaps", "revenue.view", "revenue.capture", "revenue.no_earnings", "revenue.correct", "pettycash.spend", "reports.view"],
  "Revenue clerk": ["dash.capture", "dash.gaps", "revenue.view", "revenue.capture", "revenue.no_earnings"],
};

export function PeopleAccessView() {
  const [people, setPeople] = useState<Person[]>([]); const [groups, setGroups] = useState<PermissionGroup[]>([]); const [roles, setRoles] = useState<Role[]>([]); const [editing, setEditing] = useState<Person>(); const [notice, setNotice] = useState("");
  async function reload() { try { const [page, catalog, availableRoles] = await Promise.all([requestSetup<Page<Person>>("people"), requestSetup<PermissionGroup[]>("access/catalog"), requestSetup<Role[]>("access/roles")]); setPeople(page.items); setGroups(catalog); setRoles(availableRoles); } catch (error) { setNotice((error as Error).message); } }
  useEffect(() => { void reload(); }, []);
  if (editing) return <PersonEditor person={editing.id ? editing : undefined} groups={groups} roles={roles} onCancel={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); void reload(); }} />;
  const empty: Person = { id: "", firstName: "", lastName: "", email: "", phoneNumber: "", role: roles[0]?.name || "Revenue clerk", active: true, scopeMode: "vehicles", companyIds: [], vehicleIds: [], permissions: [], hasPin: false };
  async function lifecycle(person: Person, action: "activate" | "deactivate" | "sign-out") { try { await requestSetup(`people/${person.id}/${action}`, { method: "POST" }); setNotice("Changes saved."); await reload(); } catch (error) { setNotice((error as Error).message); } }
  return <section><p className="eyebrow">Organization access</p><h1>People and access</h1><p className="muted">Manage sign-in, roles, permissions, and data scope.</p>{notice && <p className="error-box" role="status">{notice}</p>}<div className="toolbar"><span>{people.length} people in your scope</span><button onClick={() => setEditing(empty)}>Add person</button></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Role</th><th>Mobile</th><th>Sign in</th><th>Actions</th></tr></thead><tbody>{people.map((person) => <tr key={person.id}><td>{person.firstName} {person.lastName}<small>{person.email}</small></td><td>{person.role}</td><td>{person.phoneNumber}</td><td><span className={`status ${person.active ? person.hasPin ? "status-ok" : "status-warn" : "status-off"}`}>{person.active ? person.hasPin ? "Active" : "Waiting for first sign in" : "No access"}</span></td><td><button onClick={() => setEditing(person)}>Edit</button> <button onClick={() => void lifecycle(person, person.active ? "deactivate" : "activate")}>{person.active ? "Deactivate" : "Activate"}</button> <button onClick={() => void lifecycle(person, "sign-out")}>Sign out devices</button></td></tr>)}</tbody></table></div></section>;
}

function PersonEditor({ person, groups, roles, onCancel, onSaved }: { person?: Person; groups: PermissionGroup[]; roles: Role[]; onCancel: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<Person>(person || { id: "", firstName: "", lastName: "", email: "", phoneNumber: "", role: roles[0]?.name || "Revenue clerk", active: true, scopeMode: "vehicles", companyIds: [], vehicleIds: [], permissions: [], hasPin: false }); const [error, setError] = useState("");
  const allPermissions = groups.flatMap((group) => group.items); const selected = form.permissions.length ? form.permissions : form.role === "Owner" ? allPermissions.map((item) => item.key) : roleDefaults[form.role] || [];
  function toggle(item: Permission) { const next = new Set(selected); if (next.has(item.key)) { next.delete(item.key); allPermissions.filter((candidate) => candidate.needs.includes(item.key)).forEach((candidate) => next.delete(candidate.key)); } else { next.add(item.key); item.needs.forEach((need) => next.add(need)); } setForm({ ...form, permissions: [...next] }); }
  async function save() { const { id, active, hasPin, ...input } = form; try { await requestSetup(id ? `people/${id}` : "people", { method: id ? "PUT" : "POST", body: JSON.stringify({ ...input, permissions: selected }) }); onSaved(); } catch (reason) { setError((reason as Error).message); } }
  return <section className="person-form"><h1>{form.id ? `${form.firstName} ${form.lastName}` : "Add person"}</h1><p className="muted">They set their PIN with an email verification code after being added.</p><div className="form-grid">{(["firstName", "lastName", "email", "phoneNumber"] as const).map((field) => <label key={field}>{field === "phoneNumber" ? "Mobile number" : field}<input value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} /></label>)}</div><label>Role<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value, permissions: [] })}>{roles.map((role) => <option key={role.id}>{role.name}</option>)}</select></label><label>Data scope<select value={form.scopeMode} onChange={(event) => setForm({ ...form, scopeMode: event.target.value })}><option value="vehicles">Chosen vehicles</option><option value="companies">Chosen companies</option><option value="all">All companies</option></select></label><fieldset><legend>Permissions</legend>{groups.map((group) => <div key={group.name}><strong>{group.name}</strong>{group.items.map((item) => <label className="permission" key={item.key}><input type="checkbox" checked={selected.includes(item.key)} onChange={() => toggle(item)} /><span>{item.label}</span></label>)}</div>)}</fieldset>{error && <p className="error-box" role="alert">{error}</p>}<button onClick={() => void save()}>Save person</button> <button onClick={onCancel}>Cancel</button></section>;
}
